DROP DATABASE IF EXISTS `WASDE_REPORT_DB`;
CREATE DATABASE `WASDE_REPORT_DB`;
USE `WASDE_REPORT_DB`;

CREATE TABLE WASDE_REPORT (
    WR_NO INT NOT NULL,
    commodity VARCHAR(50),
    country VARCHAR(50),
    wr_description VARCHAR(500),
    PRIMARY KEY (WR_NO)
);
ALTER TABLE WASDE_REPORT DROP PRIMARY KEY;

ALTER TABLE WASDE_REPORT MODIFY WR_NO INT AUTO_INCREMENT PRIMARY KEY;

INSERT INTO WASDE_REPORT (WR_NO, commodity, country, wr_description)
VALUES
(1,'Wheat', 'USA', 'Wheat product available in USA'),
(2,'Corn', 'UK','Corn product available in UK');

SELECT * FROM WASDE_REPORT_DB.WASDE_REPORT;