"""
LLM Basic Example (open AI)
Model : OpenAI
modelname: gpt-3.5-turbo
user prompt: "What is the capital of India?" (This is the question or instruction given to the model. The model will generate a response based on this prompt.)
system prompt: You are a helpful assistant. (Gives to Model with exact Instruction to be a helpful assistant. So it avoid to halacuinate and give more accurate answer.)
temperature: 0.7  (This Temperature is used to control the randomness of the output. Higher values will make the output more random, while lower values will make it more focused and deterministic.)
Assistent Response: "The capital of India is New Delhi." (Output: This is the response generated by the model based on the user prompt and system prompt.)
Max tokens: 100 (This Max tokens is used to limit the maximum number of tokens in the generated response. It helps to control the length of the output.)
"""

import os
from urllib import response
from openai import OpenAI
from dotenv import load_dotenv

load_dotenv()
OPEN_AI_API_KEY = os.environ.get("OPEN_AI_API_KEY")
from languagemodel import LanguageModel, ModelProvider, ModelId

client = OpenAI(api_key=OPEN_AI_API_KEY)
language_model = LanguageModel(
    model_provider=ModelProvider.OPEN_AI,
    model_id=ModelId.OPEN_AI_GPT_4_1_MINI,
    api_key=OPEN_AI_API_KEY,
    temperature=0.1,
)


def get_llm_response(prompt: str):
    response = client.responses.create(
        model=language_model.model_id,
        input=[
            {
                "role": "system",
                "content": "You are a precise assistant. Answer in one line only.",
            },
            {
                "role": "user",
                "content": prompt,
            },
        ],
        max_output_tokens=100,
        temperature=language_model.temperature,
    )
    print(response.output_text)


if __name__ == "__main__":
    get_llm_response("When will the next cricket world cup be held?")
