DROP DATABASE IF EXISTS `INVENTORY_MGMT_DB`;
CREATE DATABASE `INVENTORY_MGMT_DB`;
USE `INVENTORY_MGMT_DB`;

CREATE TABLE PRODUCT_DETAILS (
    PRD_ID INT NOT NULL AUTO_INCREMENT,
    PRD_NAME VARCHAR(50),
    PRD_CATEGORY VARCHAR(100),
	PRD_QTY FLOAT(10,2),
    PRD_PRICE FLOAT(10,2),
	PRD_SUPPLIER VARCHAR(100),
	PRD_ROLE VARCHAR(50),
	PRD_CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRD_UPDATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (PRD_ID)
);

INSERT INTO PRODUCT_DETAILS (PRD_ID, PRD_NAME, PRD_CATEGORY, PRD_QTY,PRD_PRICE,PRD_SUPPLIER,PRD_ROLE)
VALUES
(1,'Wheat', 'Ags', 100,15.2,'Nestle_supplier','admin'),
(2,'Corn', 'Ags', 100,15.2,'ITC_supplier','reader');

SELECT * FROM INVENTORY_MGMT_DB.PRODUCT_DETAILS;